services:
  # Laravel Application
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: devtime-app
    restart: unless-stopped
    environment:
      - APP_ENV=production
      - APP_DEBUG=false
      - APP_KEY=base64:S+xqS/tMQ7/gM6VppBPk2GF3iSY6Ih8cI3z5dqxg5WE=
      - DB_CONNECTION=mysql
      - DB_HOST=db
      - DB_PORT=3306
      - DB_DATABASE=devtime
      - DB_USERNAME=devtime
      - DB_PASSWORD=devtime
      - CACHE_STORE=file
      - SESSION_DRIVER=file
      - QUEUE_CONNECTION=sync
    volumes:
      - .:/var/www/html
      - /var/www/html/vendor
      - /var/www/html/node_modules
    ports:
      - "8000:80"
    depends_on:
      - db
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost/"]
      interval: 30s
      timeout: 10s
      retries: 3
    networks:
      - devtime-network

  # MySQL Database
  db:
    image: mysql:8.0
    container_name: devtime-db
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: devtime
      MYSQL_USER: devtime
      MYSQL_PASSWORD: devtime
      MYSQL_ROOT_PASSWORD: root_password
    volumes:
      - db_data:/var/lib/mysql
    ports:
      - "3307:3306"
    command: --default-authentication-plugin=mysql_native_password
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "devtime", "-pdevtime"]
      interval: 30s
      timeout: 10s
      retries: 3
    networks:
      - devtime-network

  # PHPMyAdmin (Optional - for database management)
  phpmyadmin:
    image: phpmyadmin:latest
    container_name: devtime-phpmyadmin
    restart: unless-stopped
    environment:
      PMA_HOST: db
      PMA_PORT: 3306
      PMA_USER: devtime
      PMA_PASSWORD: devtime
    ports:
      - "8080:80"
    depends_on:
      - db
    networks:
      - devtime-network

volumes:
  db_data:
    driver: local

networks:
  devtime-network:
    driver: bridge
