version: '3.8'

services:
  app:
    build: 
      context: .
      dockerfile: Dockerfile.simple
    container_name: devtime-app-simple
    restart: unless-stopped
    environment:
      - APP_NAME=DevTime
      - APP_ENV=local
      - APP_DEBUG=true
      - APP_KEY=base64:S+xqS/tMQ7/gM6VppBPk2GF3iSY6Ih8cI3z5dqxg5WE=
      - APP_URL=http://localhost:8000
      - DB_CONNECTION=mysql
      - DB_HOST=db
      - DB_PORT=3306
      - DB_DATABASE=devtime
      - DB_USERNAME=devtime
      - DB_PASSWORD=devtime
      - TINYMCE_API_KEY=7djntdu3j15dfkxrgs17jd2t47v41rrcdqkd1hpbhr6wj327
    volumes:
      - .:/var/www/html
      - /var/www/html/vendor
    ports:
      - "8000:80"
    depends_on:
      - db
    networks:
      - devtime-network

  db:
    image: mysql:8.0
    container_name: devtime-db-simple
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: devtime
      MYSQL_USER: devtime
      MYSQL_PASSWORD: devtime
      MYSQL_ROOT_PASSWORD: devtime
    volumes:
      - mysql_data:/var/lib/mysql
    ports:
      - "3307:3306"
    networks:
      - devtime-network

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: devtime-phpmyadmin-simple
    restart: unless-stopped
    environment:
      PMA_HOST: db
      PMA_PORT: 3306
      PMA_USER: devtime
      PMA_PASSWORD: devtime
    ports:
      - "8080:80"
    depends_on:
      - db
    networks:
      - devtime-network

volumes:
  mysql_data:

networks:
  devtime-network:
    driver: bridge
